"""Curriculum stages for gradual, visible herding skill acquisition.

The progression intentionally changes one idea at a time: first basic penning,
then larger teams, then stray recovery, then scattered recovery, and only then
pen-location generalization.
"""

# pylint: disable=too-many-lines

from __future__ import annotations

from dataclasses import fields, replace

from sheepdog.config import EnvironmentConfig, LabConfig

def _mix(**weights: float) -> dict[str, float]:
    """Small helper to keep spawn-mixture declarations readable."""

    return {name: weight for name, weight in weights.items() if weight > 0.0}


CURRICULUM_STAGES: dict[int, dict[str, object]] = {
    1: {
        "dogs": 1,
        "sheep": 1,
        "width": 60,
        "height": 45,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.75,
        "sheep_speed": 1,
        "max_steps": 600,
        "no_progress_window": 240,
        "no_progress_distance_delta": 0.15,
        "curriculum_stage": 1,
        "spawn_mix": _mix(fixed_easy=1.0),
        "pen_placement": "corner",
    },
    2: {
        "dogs": 1,
        "sheep": 1,
        "width": 60,
        "height": 45,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.75,
        "sheep_speed": 1,
        "max_steps": 640,
        "no_progress_window": 250,
        "no_progress_distance_delta": 0.14,
        "curriculum_stage": 2,
        "spawn_mix": _mix(fixed_easy=0.7, randomized_flock=0.3),
        "pen_placement": "corner",
    },
    3: {
        "dogs": 1,
        "sheep": 2,
        "width": 60,
        "height": 45,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.8,
        "sheep_speed": 1,
        "max_steps": 700,
        "no_progress_window": 260,
        "no_progress_distance_delta": 0.14,
        "curriculum_stage": 3,
        "spawn_mix": _mix(fixed_easy=0.8, randomized_flock=0.2),
        "pen_placement": "corner",
    },
    4: {
        "dogs": 1,
        "sheep": 2,
        "width": 72,
        "height": 54,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.8,
        "sheep_speed": 1,
        "max_steps": 760,
        "no_progress_window": 280,
        "no_progress_distance_delta": 0.15,
        "curriculum_stage": 4,
        "spawn_mix": _mix(fixed_easy=0.6, randomized_flock=0.4),
        "pen_placement": "corner",
    },
    5: {
        "dogs": 2,
        "sheep": 3,
        "width": 84,
        "height": 60,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.9,
        "sheep_speed": 1,
        "max_steps": 860,
        "no_progress_window": 220,
        "no_progress_distance_delta": 0.16,
        "curriculum_stage": 5,
        "spawn_mix": _mix(fixed_easy=0.8, randomized_flock=0.2),
        "pen_placement": "corner",
    },
    6: {
        "dogs": 2,
        "sheep": 3,
        "width": 96,
        "height": 72,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.9,
        "sheep_speed": 1,
        "max_steps": 920,
        "no_progress_window": 230,
        "no_progress_distance_delta": 0.16,
        "curriculum_stage": 6,
        "spawn_mix": _mix(fixed_easy=0.6, randomized_flock=0.35, nearby_stray=0.05),
        "stray_near_min": 5.0,
        "stray_near_max": 7.0,
        "pen_placement": "corner",
    },
    7: {
        "dogs": 2,
        "sheep": 4,
        "width": 96,
        "height": 72,
        "pen_width": 12,
        "pen_height": 12,
        "pen_opening": "bottom",
        "dog_speed": 1.95,
        "sheep_speed": 1,
        "max_steps": 980,
        "no_progress_window": 240,
        "no_progress_distance_delta": 0.16,
        "sheep_personality_strength": 0.25,
        "curriculum_stage": 7,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.45, randomized_flock=0.45, nearby_stray=0.1),
        "stray_near_min": 6.0,
        "stray_near_max": 9.0,
        "pen_placement": "corner",
    },
    8: {
        "dogs": 3,
        "sheep": 4,
        "width": 108,
        "height": 78,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1040,
        "no_progress_window": 260,
        "no_progress_distance_delta": 0.15,
        "curriculum_stage": 8,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.3, randomized_flock=0.55, nearby_stray=0.15),
        "stray_near_min": 7.0,
        "stray_near_max": 10.0,
        "pen_placement": "corner",
    },
    9: {
        "dogs": 3,
        "sheep": 4,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1180,
        "no_progress_window": 320,
        "no_progress_distance_delta": 0.12,
        "curriculum_stage": 9,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.15, randomized_flock=0.6, nearby_stray=0.25),
        "stray_near_min": 8.0,
        "stray_near_max": 12.0,
        "pen_placement": "corner",
    },
    10: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1200,
        "no_progress_window": 320,
        "no_progress_distance_delta": 0.12,
        "curriculum_stage": 10,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.15, randomized_flock=0.6, nearby_stray=0.225, farther_stray=0.025),
        "stray_near_min": 8.0,
        "stray_near_max": 12.0,
        "stray_far_min": 12.0,
        "stray_far_max": 16.0,
        "pen_placement": "corner",
        "success_threshold": 0.70,
    },
    11: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1220,
        "no_progress_window": 330,
        "no_progress_distance_delta": 0.12,
        "curriculum_stage": 11,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.15, randomized_flock=0.55, nearby_stray=0.25, farther_stray=0.05),
        "stray_near_min": 9.0,
        "stray_near_max": 13.0,
        "stray_far_min": 14.0,
        "stray_far_max": 19.0,
        "pen_placement": "corner",
        "success_threshold": 0.72,
    },
    12: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1240,
        "no_progress_window": 340,
        "no_progress_distance_delta": 0.11,
        "curriculum_stage": 12,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.1, randomized_flock=0.55, nearby_stray=0.275, farther_stray=0.075),
        "stray_near_min": 10.0,
        "stray_near_max": 14.0,
        "stray_far_min": 16.0,
        "stray_far_max": 22.0,
        "pen_placement": "corner",
        "success_threshold": 0.75,
    },
    13: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1260,
        "no_progress_window": 350,
        "no_progress_distance_delta": 0.11,
        "curriculum_stage": 13,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.1, randomized_flock=0.5, nearby_stray=0.3, farther_stray=0.1),
        "stray_near_min": 11.0,
        "stray_near_max": 15.0,
        "stray_far_min": 18.0,
        "stray_far_max": 25.0,
        "pen_placement": "corner",
        "success_threshold": 0.78,
    },
    14: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1280,
        "no_progress_window": 360,
        "no_progress_distance_delta": 0.11,
        "curriculum_stage": 14,
        "count_collection_progress": True,
        "spawn_mix": _mix(fixed_easy=0.1, randomized_flock=0.5, nearby_stray=0.3, farther_stray=0.1),
        "stray_near_min": 12.0,
        "stray_near_max": 18.0,
        "stray_far_min": 18.0,
        "stray_far_max": 26.0,
        "pen_placement": "corner",
        "success_threshold": 0.9,
    },
    15: {
        "dogs": 3,
        "sheep": 5,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1340,
        "no_progress_window": 390,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 15,
        "count_collection_progress": True,
        "spawn_mix": _mix(randomized_flock=0.35, nearby_stray=0.3, farther_stray=0.25, split_flock=0.1),
        "stray_near_min": 12.0,
        "stray_near_max": 18.0,
        "stray_far_min": 18.0,
        "stray_far_max": 28.0,
        "pen_placement": "corner",
        "success_threshold": 0.9,
    },
    16: {
        "dogs": 3,
        "sheep": 6,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1360,
        "no_progress_window": 400,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 16,
        "count_collection_progress": True,
        "spawn_mix": _mix(randomized_flock=0.5, nearby_stray=0.35, farther_stray=0.15),
        "stray_near_min": 8.0,
        "stray_near_max": 12.0,
        "stray_far_min": 12.0,
        "stray_far_max": 18.0,
        "pen_placement": "corner",
        "success_threshold": 0.75,
    },
    17: {
        "dogs": 3,
        "sheep": 6,
        "width": 120,
        "height": 84,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1420,
        "no_progress_window": 430,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 17,
        "count_collection_progress": True,
        "spawn_mix": _mix(randomized_flock=0.35, nearby_stray=0.35, farther_stray=0.2, split_flock=0.1),
        "stray_near_min": 10.0,
        "stray_near_max": 16.0,
        "stray_far_min": 20.0,
        "stray_far_max": 30.0,
        "pen_placement": "corner",
    },
    18: {
        "dogs": 3,
        "sheep": 6,
        "width": 126,
        "height": 90,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1480,
        "no_progress_window": 450,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 18,
        "count_collection_progress": True,
        "spawn_mix": _mix(nearby_stray=0.4, two_strays=0.3, farther_stray=0.2, split_flock=0.1),
        "stray_near_min": 8.0,
        "stray_near_max": 14.0,
        "stray_far_min": 18.0,
        "stray_far_max": 28.0,
        "pen_placement": "corner",
    },
    19: {
        "dogs": 3,
        "sheep": 6,
        "width": 126,
        "height": 90,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1520,
        "no_progress_window": 460,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 19,
        "count_collection_progress": True,
        "spawn_mix": _mix(split_flock=0.5, randomized_flock=0.2, nearby_stray=0.2, farther_stray=0.1),
        "stray_near_min": 10.0,
        "stray_near_max": 16.0,
        "stray_far_min": 20.0,
        "stray_far_max": 30.0,
        "pen_placement": "corner",
    },
    20: {
        "dogs": 3,
        "sheep": 6,
        "width": 126,
        "height": 90,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1540,
        "no_progress_window": 465,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 20,
        "count_collection_progress": True,
        "spawn_mix": _mix(split_flock=0.35, partial_scattered=0.3, randomized_flock=0.15, nearby_stray=0.1, farther_stray=0.1),
        "pen_placement": "corner",
    },
    21: {
        "dogs": 3,
        "sheep": 6,
        "width": 126,
        "height": 90,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1560,
        "no_progress_window": 470,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 21,
        "count_collection_progress": True,
        "spawn_mix": _mix(partial_scattered=0.5, split_flock=0.25, nearby_stray=0.15, farther_stray=0.1),
        "pen_placement": "corner",
    },
    22: {
        "dogs": 3,
        "sheep": 6,
        "width": 126,
        "height": 90,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1600,
        "no_progress_window": 480,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 22,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.55, partial_scattered=0.25, split_flock=0.1, farther_stray=0.1),
        "pen_placement": "corner",
    },
    23: {
        "dogs": 3,
        "sheep": 6,
        "width": 132,
        "height": 96,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1660,
        "no_progress_window": 500,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 23,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.35, partial_scattered=0.25, split_flock=0.2, farther_stray=0.1, nearby_stray=0.1),
        "pen_placement": "same_wall",
    },
    24: {
        "dogs": 3,
        "sheep": 6,
        "width": 132,
        "height": 96,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1720,
        "no_progress_window": 520,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 24,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.35, partial_scattered=0.2, split_flock=0.2, farther_stray=0.15, nearby_stray=0.1),
        "pen_placement": "any_wall",
    },
    25: {
        "dogs": 3,
        "sheep": 6,
        "width": 132,
        "height": 96,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1760,
        "no_progress_window": 530,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 25,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.35, partial_scattered=0.2, split_flock=0.2, farther_stray=0.15, nearby_stray=0.1),
        "pen_placement": "away_from_corner",
    },
    26: {
        "dogs": 3,
        "sheep": 6,
        "width": 132,
        "height": 96,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1820,
        "no_progress_window": 560,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 26,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.4, partial_scattered=0.2, split_flock=0.2, farther_stray=0.1, nearby_stray=0.1),
        "pen_placement": "interior",
    },
    27: {
        "dogs": 3,
        "sheep": 6,
        "width": 132,
        "height": 96,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1900,
        "no_progress_window": 600,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 27,
        "count_collection_progress": True,
        "spawn_mix": _mix(randomized_flock=0.25, nearby_stray=0.2, farther_stray=0.2, split_flock=0.15, partial_scattered=0.1, scattered_sheep=0.1),
        "pen_placement": "random",
    },
    28: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 1980,
        "no_progress_window": 640,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 28,
        "count_collection_progress": True,
        "spawn_mix": _mix(farther_stray=0.4, split_flock=0.3, two_strays=0.3),
        "stray_near_min": 16.0,
        "stray_near_max": 26.0,
        "stray_far_min": 30.0,
        "stray_far_max": 44.0,
        "pen_placement": "random",
    },
    29: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2060,
        "no_progress_window": 680,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 29,
        "count_collection_progress": True,
        "spawn_mix": _mix(scattered_sheep=0.6, randomized_flock=0.2, split_flock=0.2),
        "pen_placement": "random",
    },
    30: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2140,
        "no_progress_window": 700,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 30,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=1.0),
        "pen_placement": "random",
    },
    31: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2190,
        "no_progress_window": 720,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 31,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.7, split_flock=0.2, randomized_flock=0.1),
        "pen_placement": "random",
        "sheep_personality_strength": 0.0,
    },
    32: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2240,
        "no_progress_window": 740,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 32,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.35, scattered_sheep=0.35, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 30.0,
        "stray_far_max": 44.0,
        "pen_placement": "random",
        "sheep_personality_strength": 0.0,
    },
    33: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2280,
        "no_progress_window": 760,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 33,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.3, scattered_sheep=0.4, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 32.0,
        "stray_far_max": 46.0,
        "pen_placement": "random",
        "sheep_personality_strength": 0.35,
    },
    34: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "max_steps": 2320,
        "no_progress_window": 780,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 34,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.25, scattered_sheep=0.45, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 34.0,
        "stray_far_max": 48.0,
        "pen_placement": "random",
        "sheep_personality_strength": 0.7,
    },
    35: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "sheep_flock_cohesion_weight": 0.2,
        "sheep_cohere_without_dog_pressure": True,
        "max_steps": 2340,
        "no_progress_window": 790,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 35,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.22, scattered_sheep=0.48, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 35.0,
        "stray_far_max": 49.0,
        "pen_placement": "random",
        "sheep_personality_strength": 0.7,
    },
    36: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "sheep_flock_cohesion_weight": 0.18,
        "sheep_cohere_without_dog_pressure": False,
        "max_steps": 2360,
        "no_progress_window": 800,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 36,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.2, scattered_sheep=0.5, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 36.0,
        "stray_far_max": 50.0,
        "pen_placement": "random",
        "sheep_personality_strength": 0.7,
    },
    37: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "sheep_flock_cohesion_weight": 0.16,
        "sheep_cohere_without_dog_pressure": False,
        "max_steps": 2400,
        "no_progress_window": 820,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 37,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.15, scattered_sheep=0.55, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 38.0,
        "stray_far_max": 52.0,
        "pen_placement": "random",
        "sheep_personality_strength": 1.0,
    },
    38: {
        "dogs": 3,
        "sheep": 6,
        "width": 144,
        "height": 104,
        "pen_width": 14,
        "pen_height": 14,
        "pen_opening": "bottom",
        "dog_speed": 2.0,
        "sheep_speed": 1,
        "sheep_flock_cohesion_weight": 0.12,
        "sheep_cohere_without_dog_pressure": False,
        "max_steps": 2440,
        "no_progress_window": 840,
        "no_progress_distance_delta": 0.1,
        "curriculum_stage": 38,
        "count_collection_progress": True,
        "spawn_mix": _mix(all_corners=0.1, scattered_sheep=0.6, split_flock=0.2, farther_stray=0.1),
        "stray_far_min": 40.0,
        "stray_far_max": 54.0,
        "pen_placement": "random",
        "sheep_personality_strength": 1.25,
    },
}

CURRICULUM_REWARD_OVERRIDES: dict[int, dict[str, object]] = {
    7: {
        "time_penalty": 0.019,
        "no_progress_penalty": 0.028,
        "flock_cohesion_scale": 0.72,
        "scatter_penalty_scale": 0.28,
        "farthest_sheep_progress_scale": 0.35,
        "stray_ignore_penalty_scale": 0.0035,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 76.0,
    },
    8: {
        "time_penalty": 0.0195,
        "no_progress_penalty": 0.029,
        "flock_cohesion_scale": 0.69,
        "scatter_penalty_scale": 0.28,
        "farthest_sheep_progress_scale": 0.42,
        "stray_ignore_penalty_scale": 0.004,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 76.0,
    },
    9: {
        "time_penalty": 0.02,
        "no_progress_penalty": 0.03,
        "flock_cohesion_scale": 0.7,
        "scatter_penalty_scale": 0.3,
        "farthest_sheep_progress_scale": 0.5,
        "stray_ignore_penalty_scale": 0.005,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    10: {
        "time_penalty": 0.021,
        "no_progress_penalty": 0.032,
        "flock_cohesion_scale": 0.68,
        "scatter_penalty_scale": 0.32,
        "farthest_sheep_progress_scale": 0.55,
        "stray_ignore_penalty_scale": 0.0055,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    11: {
        "time_penalty": 0.021,
        "no_progress_penalty": 0.032,
        "flock_cohesion_scale": 0.68,
        "scatter_penalty_scale": 0.32,
        "farthest_sheep_progress_scale": 0.55,
        "stray_ignore_penalty_scale": 0.0055,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    12: {
        "time_penalty": 0.021,
        "no_progress_penalty": 0.032,
        "flock_cohesion_scale": 0.68,
        "scatter_penalty_scale": 0.32,
        "farthest_sheep_progress_scale": 0.55,
        "stray_ignore_penalty_scale": 0.0055,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    13: {
        "time_penalty": 0.021,
        "no_progress_penalty": 0.032,
        "flock_cohesion_scale": 0.68,
        "scatter_penalty_scale": 0.32,
        "farthest_sheep_progress_scale": 0.55,
        "stray_ignore_penalty_scale": 0.0055,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    14: {
        "time_penalty": 0.021,
        "no_progress_penalty": 0.032,
        "flock_cohesion_scale": 0.68,
        "scatter_penalty_scale": 0.32,
        "farthest_sheep_progress_scale": 0.55,
        "stray_ignore_penalty_scale": 0.0055,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 75.0,
    },
    15: {
        "time_penalty": 0.022,
        "no_progress_penalty": 0.034,
        "flock_cohesion_scale": 0.66,
        "scatter_penalty_scale": 0.34,
        "farthest_sheep_progress_scale": 0.6,
        "stray_ignore_penalty_scale": 0.006,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 74.0,
    },
    16: {
        "time_penalty": 0.023,
        "no_progress_penalty": 0.036,
        "flock_cohesion_scale": 0.64,
        "scatter_penalty_scale": 0.36,
        "farthest_sheep_progress_scale": 0.65,
        "stray_ignore_penalty_scale": 0.0065,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 73.0,
    },
    17: {
        "time_penalty": 0.023,
        "no_progress_penalty": 0.036,
        "flock_cohesion_scale": 0.64,
        "scatter_penalty_scale": 0.36,
        "farthest_sheep_progress_scale": 0.65,
        "stray_ignore_penalty_scale": 0.0065,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 73.0,
    },
    18: {
        "time_penalty": 0.024,
        "no_progress_penalty": 0.038,
        "flock_cohesion_scale": 0.62,
        "scatter_penalty_scale": 0.38,
        "farthest_sheep_progress_scale": 0.7,
        "stray_ignore_penalty_scale": 0.007,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 72.0,
    },
    19: {
        "time_penalty": 0.025,
        "no_progress_penalty": 0.04,
        "flock_cohesion_scale": 0.6,
        "scatter_penalty_scale": 0.4,
        "farthest_sheep_progress_scale": 0.75,
        "stray_ignore_penalty_scale": 0.0075,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 72.0,
    },
    20: {
        "time_penalty": 0.0255,
        "no_progress_penalty": 0.041,
        "flock_cohesion_scale": 0.59,
        "scatter_penalty_scale": 0.41,
        "farthest_sheep_progress_scale": 0.775,
        "stray_ignore_penalty_scale": 0.00775,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 71.5,
    },
    21: {
        "time_penalty": 0.026,
        "no_progress_penalty": 0.042,
        "flock_cohesion_scale": 0.58,
        "scatter_penalty_scale": 0.42,
        "farthest_sheep_progress_scale": 0.8,
        "stray_ignore_penalty_scale": 0.008,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 71.0,
    },
    22: {
        "time_penalty": 0.027,
        "no_progress_penalty": 0.044,
        "flock_cohesion_scale": 0.56,
        "scatter_penalty_scale": 0.44,
        "farthest_sheep_progress_scale": 0.85,
        "stray_ignore_penalty_scale": 0.0085,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 70.0,
    },
    23: {
        "time_penalty": 0.028,
        "no_progress_penalty": 0.045,
        "flock_cohesion_scale": 0.55,
        "scatter_penalty_scale": 0.45,
        "farthest_sheep_progress_scale": 0.9,
        "stray_ignore_penalty_scale": 0.009,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 70.0,
    },
    24: {
        "time_penalty": 0.029,
        "no_progress_penalty": 0.046,
        "flock_cohesion_scale": 0.54,
        "scatter_penalty_scale": 0.46,
        "farthest_sheep_progress_scale": 0.92,
        "stray_ignore_penalty_scale": 0.00925,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 69.0,
    },
    25: {
        "time_penalty": 0.029,
        "no_progress_penalty": 0.047,
        "flock_cohesion_scale": 0.53,
        "scatter_penalty_scale": 0.47,
        "farthest_sheep_progress_scale": 0.95,
        "stray_ignore_penalty_scale": 0.0095,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 68.0,
    },
    26: {
        "time_penalty": 0.03,
        "no_progress_penalty": 0.048,
        "flock_cohesion_scale": 0.52,
        "scatter_penalty_scale": 0.48,
        "farthest_sheep_progress_scale": 0.98,
        "stray_ignore_penalty_scale": 0.00975,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 68.0,
    },
    27: {
        "time_penalty": 0.03,
        "no_progress_penalty": 0.05,
        "flock_cohesion_scale": 0.5,
        "scatter_penalty_scale": 0.5,
        "farthest_sheep_progress_scale": 1.0,
        "stray_ignore_penalty_scale": 0.01,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 67.0,
    },
    28: {
        "time_penalty": 0.031,
        "no_progress_penalty": 0.051,
        "flock_cohesion_scale": 0.49,
        "scatter_penalty_scale": 0.52,
        "farthest_sheep_progress_scale": 1.03,
        "stray_ignore_penalty_scale": 0.0105,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 66.0,
    },
    29: {
        "time_penalty": 0.032,
        "no_progress_penalty": 0.052,
        "flock_cohesion_scale": 0.48,
        "scatter_penalty_scale": 0.54,
        "farthest_sheep_progress_scale": 1.05,
        "stray_ignore_penalty_scale": 0.011,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 65.0,
    },
    30: {
        "time_penalty": 0.033,
        "no_progress_penalty": 0.053,
        "flock_cohesion_scale": 0.47,
        "scatter_penalty_scale": 0.55,
        "farthest_sheep_progress_scale": 1.08,
        "stray_ignore_penalty_scale": 0.0115,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 64.0,
    },
    31: {
        "time_penalty": 0.0335,
        "no_progress_penalty": 0.054,
        "flock_cohesion_scale": 0.465,
        "scatter_penalty_scale": 0.56,
        "farthest_sheep_progress_scale": 1.09,
        "stray_ignore_penalty_scale": 0.01175,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 63.5,
    },
    32: {
        "time_penalty": 0.034,
        "no_progress_penalty": 0.055,
        "flock_cohesion_scale": 0.46,
        "scatter_penalty_scale": 0.57,
        "farthest_sheep_progress_scale": 1.1,
        "stray_ignore_penalty_scale": 0.012,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 63.0,
    },
    33: {
        "time_penalty": 0.035,
        "no_progress_penalty": 0.056,
        "flock_cohesion_scale": 0.44,
        "scatter_penalty_scale": 0.58,
        "farthest_sheep_progress_scale": 1.12,
        "stray_ignore_penalty_scale": 0.0125,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 62.0,
    },
    34: {
        "time_penalty": 0.036,
        "no_progress_penalty": 0.057,
        "flock_cohesion_scale": 0.42,
        "scatter_penalty_scale": 0.59,
        "farthest_sheep_progress_scale": 1.14,
        "stray_ignore_penalty_scale": 0.013,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 61.0,
    },
    35: {
        "time_penalty": 0.0365,
        "no_progress_penalty": 0.0575,
        "flock_cohesion_scale": 0.41,
        "scatter_penalty_scale": 0.595,
        "farthest_sheep_progress_scale": 1.15,
        "stray_ignore_penalty_scale": 0.01325,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 60.5,
    },
    36: {
        "time_penalty": 0.037,
        "no_progress_penalty": 0.058,
        "flock_cohesion_scale": 0.4,
        "scatter_penalty_scale": 0.6,
        "farthest_sheep_progress_scale": 1.16,
        "stray_ignore_penalty_scale": 0.0135,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 60.0,
    },
    37: {
        "time_penalty": 0.038,
        "no_progress_penalty": 0.059,
        "flock_cohesion_scale": 0.39,
        "scatter_penalty_scale": 0.61,
        "farthest_sheep_progress_scale": 1.18,
        "stray_ignore_penalty_scale": 0.014,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 59.0,
    },
    38: {
        "time_penalty": 0.039,
        "no_progress_penalty": 0.06,
        "flock_cohesion_scale": 0.38,
        "scatter_penalty_scale": 0.62,
        "farthest_sheep_progress_scale": 1.2,
        "stray_ignore_penalty_scale": 0.0145,
        "sheep_penned_reward": 10.0,
        "terminal_success_reward": 58.0,
    },
}

# Hyperparameter overrides for transitional/challenging stages to boost exploration
CURRICULUM_TRAINING_OVERRIDES: dict[int, dict[str, object]] = {
    # transitional 5-sheep stages (boost entropy, set slightly higher learning rates, GAE lambda=0.98)
    10: {"entropy_coef": 0.015, "learning_rate": 1.2e-4, "learning_rate_final": 5e-5, "gae_lambda": 0.98},
    11: {"entropy_coef": 0.015, "learning_rate": 1.2e-4, "learning_rate_final": 5e-5, "gae_lambda": 0.98},
    12: {"entropy_coef": 0.015, "learning_rate": 1.2e-4, "learning_rate_final": 5e-5, "gae_lambda": 0.98},
    13: {"entropy_coef": 0.015, "learning_rate": 1.2e-4, "learning_rate_final": 5e-5, "gae_lambda": 0.98},
    # mastery stages (lock back to baseline exploration/learning rates)
    14: {"entropy_coef": 0.010, "learning_rate": 1.0e-4, "learning_rate_final": 3e-5, "gae_lambda": 0.98},
    15: {"entropy_coef": 0.010, "learning_rate": 1.0e-4, "learning_rate_final": 3e-5, "gae_lambda": 0.98},
    # transitional 6-sheep stage (boost entropy)
    16: {"entropy_coef": 0.020, "learning_rate": 1.2e-4, "learning_rate_final": 4e-5},
}

def apply_curriculum_stage(config: LabConfig, stage: int) -> LabConfig:
    """Return a copy of ``config`` with the stage's environment overrides applied.

    Stage ``0`` returns the original config unchanged so curriculum is opt-in.
    """

    overrides = CURRICULUM_STAGES.get(stage)
    if not overrides:
        return config
    # Filter only keys that are actually fields of EnvironmentConfig
    env_keys = {f.name for f in fields(EnvironmentConfig)}
    env_overrides = {k: v for k, v in overrides.items() if k in env_keys}
    new_environment = replace(config.environment, **env_overrides)
    
    reward_overrides = CURRICULUM_REWARD_OVERRIDES.get(stage)
    new_rewards = replace(config.rewards, **reward_overrides) if reward_overrides else config.rewards
    
    training_overrides = CURRICULUM_TRAINING_OVERRIDES.get(stage)
    new_training = replace(config.training, **training_overrides) if training_overrides else config.training
    
    return replace(config, environment=new_environment, rewards=new_rewards, training=new_training)

def stage_summary(stage: int) -> str:
    """Return a short human-readable description of a curriculum stage."""

    descriptions = {
        1: "1 dog, 1 sheep, fixed easy placement.",
        2: "1 dog, 1 sheep, mild random starts.",
        3: "1 dog, 2 sheep, fixed easy flock.",
        4: "1 dog, 2 sheep, randomized flock start.",
        5: "2 dogs, 3 sheep, fixed easy teamwork.",
        6: "2 dogs, 3 sheep, mostly grouped with occasional tiny nearby stray.",
        7: "2 dogs, 4 sheep, early nearby stray collection starts (6-9 cells).",
        8: "3 dogs, 4 sheep, larger field with frequent nearby strays (7-10 cells).",
        9: "3 dogs, 4 sheep, nearby stray recovery emphasis (8-12 cells).",
        10: "Stage 10A: 3 dogs, 5 sheep, introductory farther stray (12-16 cells, 2.5% spawn mix).",
        11: "Stage 10B: 3 dogs, 5 sheep, scaling farther stray (14-19 cells, 5.0% spawn mix).",
        12: "Stage 10C: 3 dogs, 5 sheep, scaling farther stray (16-22 cells, 7.5% spawn mix).",
        13: "Stage 10D: 3 dogs, 5 sheep, scaling farther stray (18-25 cells, 10% spawn mix).",
        14: "Stage 14: 3 dogs, 5 sheep, farther stray mastery (18-26 cells, 10% spawn mix).",
        15: "3 dogs, 5 sheep, stronger farther stray recovery (18-28 cells, 25% spawn).",
        16: "3 dogs, 6 sheep, transitional 6 sheep introduction (12-18 cells, 15% spawn).",
        17: "3 dogs, 6 sheep, group + one stray collection.",
        18: "3 dogs, 6 sheep, two nearby strays collection.",
        19: "3 dogs, 6 sheep, split flock (3+3) recovery.",
        20: "3 dogs, 6 sheep, split-to-scatter bridge (mixed layouts).",
        21: "3 dogs, 6 sheep, partially scattered recovery.",
        22: "3 dogs, 6 sheep, scattered sheep recovery.",
        23: "3 dogs, 6 sheep, pen moves on same wall.",
        24: "3 dogs, 6 sheep, pen can be on any wall.",
        25: "3 dogs, 6 sheep, pen away from corners.",
        26: "3 dogs, 6 sheep, interior pen challenge.",
        27: "3 dogs, 6 sheep, random pen + random sheep.",
        28: "3 dogs, 6 sheep, very far stray/split recovery.",
        29: "3 dogs, 6 sheep, fully random scattered placements.",
        30: "3 dogs, 6 sheep, all sheep spawned in field corners.",
        31: "3 dogs, 6 sheep, corner-heavy bridge before hard random mixes.",
        32: "3 dogs, 6 sheep, hard spawn mix with personality bias still off.",
        33: "3 dogs, 6 sheep, phase 1 mild personality variation.",
        34: "3 dogs, 6 sheep, phase 2 moderate personality variation.",
        35: "3 dogs, 6 sheep, bridge stage with weaker cohesion but dog-pressure grouping still on.",
        36: "3 dogs, 6 sheep, disable no-pressure cohesion.",
        37: "3 dogs, 6 sheep, lower cohesion and stronger personalities.",
        38: "3 dogs, 6 sheep, lowest cohesion and strongest personalities.",
    }
    return descriptions.get(stage, "Custom stage.")


def available_stages() -> tuple[int, ...]:
    """Return the sorted tuple of available curriculum stage numbers."""

    return tuple(sorted(CURRICULUM_STAGES))


def validate_curriculum_stage(stage: int) -> int:
    """Return a normalized curriculum stage or raise for unknown non-zero values."""

    normalized = max(0, int(stage))
    if normalized == 0:
        return 0
    if normalized not in CURRICULUM_STAGES:
        choices = ", ".join(str(value) for value in available_stages())
        raise ValueError(f"Unknown curriculum stage {stage}. Available stages: {choices}")
    return normalized


def apply_training_profile(
    config: LabConfig,
    *,
    enable_instinct_rewards: bool | None = None,
    curriculum_stage: int | None = None,
    debug_reward_breakdown: bool | None = None,
) -> LabConfig:
    """Apply instinct toggles and curriculum overrides to a config copy."""

    base_instincts = config.rewards.instincts
    stage = validate_curriculum_stage(
        base_instincts.curriculum_stage if curriculum_stage is None else curriculum_stage
    )
    updated_instincts = replace(
        base_instincts,
        enable_instinct_rewards=(
            base_instincts.enable_instinct_rewards
            if enable_instinct_rewards is None
            else enable_instinct_rewards
        ),
        debug_reward_breakdown=(
            base_instincts.debug_reward_breakdown
            if debug_reward_breakdown is None
            else debug_reward_breakdown
        ),
        curriculum_stage=stage,
    )
    updated_config = replace(
        config,
        rewards=replace(config.rewards, instincts=updated_instincts),
    )
    return apply_curriculum_stage(updated_config, stage)

